# fly.toml app configuration file generated for rubik-solver on 2023-10-26T06:56:29-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "rubik-solver"
primary_region = "sjc"
kill_signal = "SIGTERM"

[build]

[deploy]
  # NOTE Database setup
  # release_command = "/app/bin/migrate"

[env]
  PHX_HOST = "rubik-solver.fly.dev"
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  processes = ["app"]
  [http_service.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 1000
